In [1]:
import numpy as np # Import the NumPy library

In [2]:
numbers  = np.array([10,20,30,40,50]) # Create a NumPy array

In [3]:
numbers # Display the complete array

array([10, 20, 30, 40, 50])

In [4]:
print(numbers) # Access the first element of the array

[10 20 30 40 50]


In [21]:
print("Array:", numbers)

Array: [10 20 30 40 50]


In [20]:
numbers[0] # Access the third element of the array


np.int64(10)

In [19]:
print("First Element:", numbers[0])

First Element: 10


In [18]:
numbers[2] # Access the last element of the array


np.int64(30)

In [17]:
print("Third Element:", numbers[2])

Third Element: 30


In [7]:
numbers[-1] # Access the second last element of the array

np.int64(50)

In [22]:
print("Last Element:", numbers[-1])

Last Element: 50


In [8]:
numbers[-2] # Add 5 to every element in the array

np.int64(40)

In [23]:
print("Second Last Element:", numbers[-2])

Second Last Element: 40


In [9]:
numbers+5 # Multiply every element by 5

array([15, 25, 35, 45, 55])

In [24]:
print("Add 5:", numbers + 5)

Add 5: [15 25 35 45 55]


In [10]:
numbers*5  # Multiply every element by 5

array([ 50, 100, 150, 200, 250])

In [25]:
print("Multiply by 5:", numbers * 5)

Multiply by 5: [ 50 100 150 200 250]


In [11]:
numbers/5  # Divide every element by 5

array([ 2.,  4.,  6.,  8., 10.])

In [26]:
print("Divide by 5:", numbers / 5)

Divide by 5: [ 2.  4.  6.  8. 10.]


In [12]:
np.mean(numbers) # Calculate the average (mean) of all elements


np.float64(30.0)

In [27]:
print("Mean:", np.mean(numbers))

Mean: 30.0


In [14]:
np.sqrt(numbers) # Calculate the square root of each element

array([3.16227766, 4.47213595, 5.47722558, 6.32455532, 7.07106781])

In [28]:
print("Square Root:", np.sqrt(numbers))

Square Root: [3.16227766 4.47213595 5.47722558 6.32455532 7.07106781]


In [29]:
print("Sum:", np.sum(numbers)) # Calculate the sum of all elements

Sum: 150


In [30]:
print("Maximum:", np.max(numbers)) # Find the largest value

Maximum: 50


In [31]:
print("Minimum:", np.min(numbers)) # Find the smallest value

Minimum: 10


In [33]:
arr_1d = np.array(numbers)

In [34]:
print(arr_1d)

[10 20 30 40 50]


In [35]:
print("Original List:", numbers)
print("NumPy 1D Array:", arr_1d)

Original List: [10 20 30 40 50]
NumPy 1D Array: [10 20 30 40 50]


In [36]:
print("Type of Array:", type(arr_1d)) #ndarray = n-dimensional Array(1D,2D,3D or many more)
## Check what type of data is stored in arr_1d

Type of Array: <class 'numpy.ndarray'>


In [37]:
print("Shape of Array:", arr_1d.shape)

Shape of Array: (5,)


In [40]:
print("2D array:  \n " ,matrix)

2D array:  
  [[1 2 3]
 [4 5 6]]


In [ ]:
# In Ml [1, 2, 3, 4, 5] its also called as Vector along array

In [41]:
numbers = [1.2,3.2,4.5,8.9] #list
print(numbers) #you need loop for performing mathmetical operation in list here  the use numPy to easier

[1.2, 3.2, 4.5, 8.9]


In [43]:
arr = np.array([1.2,3.2,4.5,8.9]) # creating numPy array

In [44]:
print("perfrom mathmetical operations: ")
print("addition operation in numPy array: ", arr+5)
print("multiplication operation in numPy array: ", arr*5)
print("mean operation in numPy array: ", np.mean(arr))
print("summation operation in numPy array: ", np.sum(arr))


perfrom mathmetical operations: 
addition operation in numPy array:  [ 6.2  8.2  9.5 13.9]
multiplication operation in numPy array:  [ 6.  16.  22.5 44.5]
mean operation in numPy array:  4.45
summation operation in numPy array:  17.8
