In [ ]:
#np.zeros(),np.ones(), np.arange(),np.linspace() theses 4 functions

import numpy as np  # Import NumPy for efficient numerical computing and array operations

In [ ]:
#np.zeros()
#np.zeros(number_of_elements)
#Create a one-dimensional array initialized with zeros
arr = np.zeros(5) # create an array with five zeros

In [ ]:
arr # Display the contents of the array(Jupyter automatically shows the output) without using print


array([0., 0., 0., 0., 0.])

In [ ]:
print (arr) # Display the array using the print() function

[0. 0. 0. 0. 0.]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
print(arr.dtype)

int64


In [ ]:
print(arr.shape)

(5,)


In [ ]:
arr = np.zeros(5, dtype=int) #if you want integar value

In [ ]:
print(arr) #dispaly integar value of array

[0 0 0 0 0]


In [ ]:
print(type(arr)) # Check the data type of the array

<class 'numpy.ndarray'>


In [ ]:
print (arr.dtype) # Check the data type of the array elements

int64


In [ ]:
print(arr.shape) # Display the shape of the array Shape returns the array dimensions as a tuple

(5,)


In [ ]:
#np.ones()
#np.ones(number_of_elements)
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [ ]:
arr = np.ones(5,dtype=int) # Create a one-dimensional array filled with integer ones
print(arr) #print
print("ones: ",arr) #print with comment

[1 1 1 1 1]
ones:  [1 1 1 1 1]


In [ ]:
# np.arange()
#np.arange(start, stop, step)
# start : Starting value (included)
# stop  : Ending value (not included)
# step  : Interval between consecutive values

arr = np.arange(1,6) # Generate a sequence of integers from 1 to 5
print(arr) #print(Note: The stop value is not included in the output)


[1 2 3 4 5]


In [ ]:
arr = np.arange(0, 10, 2)
print(arr)
print("arange: ",arr)

[0 2 4 6 8]
arange:  [0 2 4 6 8]


In [ ]:
#np.linspace()
#np.linspace(start, stop, number_of_values)
# start            : Starting value (included)
# stop             : Ending value (included)
# number_of_values : Total number of values to generate

arr =  np.linspace(0, 10, 5) # Generate five evenly spaced values from 0 to 10
print(arr) #print
print("linspace: ",arr) #print with a descriptive label

[ 0.   2.5  5.   7.5 10. ]
linspace:  [ 0.   2.5  5.   7.5 10. ]
