In [2]:
import numpy as np

In [2]:
arr = np.array([10,20,30,40,50]) # Create a one-dimensional NumPy array

In [3]:
print(arr) # Display the original array

[10 20 30 40 50]


In [4]:
print(arr[0]) # Access the first element of the array

10


In [5]:
arr[0]

np.int64(10)

In [6]:
print(arr[1]) # Access the second element of the array

20


In [7]:
print(arr[2]) # Access the third element of the array

30


In [8]:
print(arr[4]) # Access the fifth element of the array

50


In [10]:
print(arr[10]) #IndexError because array size is 5(index 0 - index 4)

IndexError: index 10 is out of bounds for axis 0 with size 5

In [11]:
print

<function print(*args, sep=' ', end='\n', file=None, flush=False)>

In [13]:
print (arr[-1]) # Access the last element of the array using negative indexing

50


In [14]:
print(arr[-2]) # Access the second last element of the array

40


In [15]:
print(arr[-3]) # Access the third last element of the array

30


In [16]:
print(arr[-5]) # Access the first element using negative indexing

10


In [17]:
print(arr[-6]) #IndexError: index -6 is out of bounds for axis 0 with size 5

IndexError: index -6 is out of bounds for axis 0 with size 5

In [20]:
slicing = np.array([3.4,5.6,7.8,9.0,6,.7]) 
# Create a one-dimensional NumPy array using floating number

In [21]:
print(arr)

[10 20 30 40 50]


In [22]:
print(arr[1:4]) # Extract elements from index 1 up to (but not including) index 4

[20 30 40]


In [23]:
print(arr[:3])# Extract the first three elements

[10 20 30]


In [26]:
print(arr[3:])

[40 50]


In [27]:
step_slicing = np.array([100,120,130,140,150])

In [28]:
print(arr)

[10 20 30 40 50]


In [31]:
print(step_slicing[::2])  # Select every second element from the array

[100 130 150]


In [32]:
print(step_slicing[::-1])

[150 140 130 120 100]


In [33]:
print(step_slicing[::3]) # Select every third element from the array


[100 140]


In [34]:
print(step_slicing[1::2]) # Select every second element starting from index 1


[120 140]


In [35]:
print(step_slicing[2:7:2])# Select every second element between index 2 and index 7 but 7 is not incuded

[130 150]


In [36]:
print(step_slicing[::-1]) 
# Reverse the array using negative step slicing

[150 140 130 120 100]


In [37]:
print(step_slicing[::-2])
# Print the array in reverse order without modifying the original array using negative step slicing

[150 130 100]


In [42]:
print(marks)

[[85 90 88]
 [78 82 80]
 [92 89 95]]


In [4]:
# Create a two-dimensional NumPy array

marks = np.array([
    [85,90,88],
    [78,82,80],
    [92,89,95]
])

In [45]:
print(marks[0,1]) # Access the second element (row 0, column 1)

90


In [46]:
print(marks[1,2]) # Access the element at row 1 and column 2

80


In [47]:
print(marks[2,1]) # Access the element at row 2 and column 1

89


In [5]:
marks[1,2]

np.int64(80)

In [12]:
# Create a two-dimensional NumPy array

marks = np.array([
    [85, 98,100],
    [56,78,89],
    [45,67,98]
])

In [13]:
print(marks)  # Display the original array

[[ 85  98 100]
 [ 56  78  89]
 [ 45  67  98]]


In [14]:
print(marks[0]) # Select the first row

[ 85  98 100]


In [15]:
print(marks[1]) # Select the second row

[56 78 89]


In [16]:
print(marks[:,0]) # Select the first column

[85 56 45]


In [17]:
print(marks[:,1])# Select the second column


[98 78 67]


In [23]:
print(marks[:,0:2]) # Select the first two columns

[[85 98]
 [56 78]
 [45 67]]


In [19]:
print(marks[0:2,0:2])# Select the first two rows and first two columns

[[85 98]
 [56 78]]


In [ ]:
#Practice 1 – Basic Indexing
# Tasks
# Print the first element.
# Print the last element using negative indexing.
# Print the third element.
# Print the second last element.

In [3]:
practice_problems_1 = np.array([5,10,15,20,25,30])

In [4]:
print(practice_problems_1[0]) #Q1 : Print the first element.

5


In [5]:
print(practice_problems_1[-1]) #Q2: Print the last element using negative indexing.

30


In [6]:
print(practice_problems_1[2]) #Q3: Print the third element.

15


In [7]:
print(practice_problems_1[-2]) #Q4: Print the second last element.

25


In [ ]:
#Practice 2 – Basic Slicing
# Tasks
# Print the first four elements.
# Print the last three elements.
# Print elements from index 2 to index 5.
# Print every second element.
# Reverse the array.

In [8]:
practice_problems_2 = np.array([5,10,20,30,40,50,60,70,80])

In [19]:
print(practice_problems_2[0:4])#Q1: Print the first four elements.
#or
print(practice_problems_2[:4])

[ 5 10 20 30]


In [13]:
#Q2: Print the last three elements.

print(practice_problems_2[-3:])
#or
print(practice_problems_2[-1:-4:-1])

[60 70 80]


In [14]:
print(practice_problems_2[2:6]) #Q3: Print elements from index 2 to index 5.

[20 30 40 50]


In [15]:
print(practice_problems_2[0:8:2]) #Q4: Print every second element.

[ 5 20 40 60]


In [17]:
print(practice_problems_2[-1:-9:-1]) #Q5: Reverse the array.

[80 70 60 50 40 30 20 10]


In [ ]:
#Practice 3 – 2D Indexing
# Print the first row.
# Print the second row.
# Print the first column.
# Print the second column.
# Print the value 95.
# Print the top-left 2×2 submatrix.Print the first row.
# Print the second row.
# Print the first column.
# Print the second column.
# Print the value 95.
# Print the top-left 2×2 submatrix.

In [24]:
practice_problems_3 = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 89, 95]
])

In [26]:
print(practice_problems_3[0])  # Select and display the first row


[85 90 88]


In [30]:
print(practice_problems_3[1]) # Select and display the second row

[78 82 80]


In [31]:
# Select and display the first column
print(practice_problems_3[:,0])  # how its work? : means all rows and 0 means column 0


[85 78 92]


In [32]:
print(practice_problems_3[:,1])  # Select and display the second column

[90 82 89]


In [34]:
print(practice_problems_3[2,2]) # Access and display the value 95

95


In [35]:
print(practice_problems_3[0:2, 0:2]) # Select and display the top-left 2×2 submatrix


[[85 90]
 [78 82]]
