In [1]:
import numpy as np

In [ ]:
# np.random.rand() function

In [2]:
random_number = np.random.rand() # Generate one random floating-point number between 0 and 1

In [3]:
print(random_number) # Display the generated random number

0.21586386507273092


In [5]:
#Generate Multiple Random Numbers

random_values = np.random.rand(5)


In [6]:
print(random_values)

[0.09841415 0.10593563 0.85949247 0.12917599 0.85296828]


In [7]:
# Generate a 2D Random Array

random_matrix = np.random.rand(3,4) # Generate a 3×4 array of random floating-point numbers

In [8]:
print(random_matrix) #print

[[0.92630037 0.98858019 0.46782973 0.02493144]
 [0.66317734 0.90250694 0.44783133 0.21469506]
 [0.73978013 0.4894605  0.64203974 0.09363176]]


In [ ]:
##Practice Problems
# Practice 1
# Generate one random floating-point number.

# Practice 2
# Generate five random floating-point numbers.

# Practice 3
# Generate a 2×3 random array.

# Practice 4
# Print the shape of the generated array.

# Practice 5
# Print the number of dimensions.

In [11]:
# Practice 1
# Generate one random floating-point number.

random = np.random.rand()
print(random)

0.7947265878438532


In [12]:
# Practice 2
# Generate five random floating-point numbers.
random = np.random.rand(5)
print(random)

[0.72449759 0.30470218 0.14742337 0.15625993 0.59249909]


In [14]:
# Practice 3
# Generate a 2×3 random array.
random = np.random.rand(2,3)
print(random)

[[0.57332831 0.23775424 0.52093017]
 [0.87328983 0.71282768 0.58806163]]


In [15]:
# Practice 4
# Print the shape of the generated array
print(random.shape)

(2, 3)


In [16]:
# Practice 5
# Print the number of dimensions.

print(random.ndim)

2


In [ ]:
# Key Takeaways
# np.random.rand() generates random decimal numbers.
# The values are always between 0 and 1.
# It can generate both 1D and 2D arrays.
# It is widely used for data simulation, testing, and machine learning experiments.

In [ ]:
#np.random.randint() function

In [27]:
random_number = np.random.randint(1,101) #Generate one random integer between 1 and 100 ,101 never comen as output

In [28]:
print(random_number) #print output will chnage in every time

8


In [31]:
marks = np.random.randint(40,101,(3,4)) # Generate a 3×4 matrix of random student marks


In [32]:
print(marks) # print

[[65 66 77 51]
 [68 92 97 86]
 [61 73 75 40]]


In [ ]:
#Practice Problems
# Practice 1
# Generate one random integer between 10 and 50.

# Practice 2
# Generate five random integers between 1 and 100.

# Practice 3
# Generate a 2×3 matrix of random integers between 20 and 80.

# Practice 4
# Print the shape of the generated matrix.

# Practice 5
# Generate ten random binary labels (0 or 1).

In [34]:
# Practice 1
# Generate one random integer between 10 and 50.
random = np.random.randint(10,50)
print(random)

47


In [37]:
# Practice 2
# Generate five random integers between 1 and 100.
random = np.random.randint(10,50,5)
print(random)

[16 45 16 13 22]


In [39]:
# Practice 3
# Generate a 2×3 matrix of random integers between 20 and 80.

random = np.random.randint(1,100,(2*3))
print(random)

[46 57  2 44 85  7]


In [40]:
# Practice 4
# Print the shape of the generated matrix.
print(random.shape)

(6,)


In [44]:
# Practice 5
# Generate ten random binary labels (0 or 1).

# random = np.random.randint(0,1,10) #incorrect coz its create only 0 ≤ value < 1
binary_labels = np.random.randint(0,2,10)
print(binary_labels)
# Why do we use 2 instead of 1?
# Because the upper limit in np.random.randint() is exclusive. To generate both 0 and 1, we use 2 as the upper limit.

[0 1 0 1 1 0 1 1 0 1]


In [ ]:
# Key Takeaways
# np.random.randint(low, high, size)
# np.random.randint() generates random integers.
# The upper limit is excluded.
# It can generate single values, 1D arrays, and 2D arrays.
# It is widely used for creating artificial datasets and labels in Machine Learning.

In [ ]:
# np functionrandom.seed() function

In [50]:
# Without Seed
print(np.random.randint(1,101,5)) #output will chage in every execution

[90 71 18 88 66]


In [55]:
#with seed

np.random.seed(42) ## Set the random seed(for this valu output will remin same till number is changed)
numbers = np.random.randint(1,101,5)
print(numbers) #output not changed in every execution

[52 93 15 72 61]


In [56]:
np.random.seed(100)
numbers = np.random.randint(1,101,5)
print(numbers) #output not changed in every execution(but change for seed value is changed)

[ 9 25 68 88 80]


In [57]:
np.random.seed(2026)
numbers = np.random.randint(1,101,5)
print(numbers) #output not changed in every execution(but change for seed value is changed)

[ 2  7 27 57 78]


In [ ]:
#Practice Problems
# Practice 1
# Set the random seed to 10 and generate five random integers.

# Practice 2
# Set the random seed to 100 and generate ten random integers between 1 and 50.

# Practice 3
# Run the same code twice and verify that the outputs are identical.

# Practice 4
# Generate a 3×3 random integer matrix using seed 7.

# Practice 5
# Change the seed value and observe how the output changes.

In [63]:
# Practice 1
# Set the random seed to 10 and generate five random integers.
np.random.seed(10)
five_random_integers = np.random.randint(1,100,5)
print(five_random_integers)

[10 16 65 29 90]


In [65]:
# Practice 2
# Set the random seed to 100 and generate ten random integers between 1 and 50.
np.random.seed(100)
ten_random_integers = np.random.randint(1,50,10)
print(ten_random_integers)


[ 9 25  4 40 24 16 49 11 31 35]


In [68]:
# Practice 3
# Run the same code twice and verify that the outputs are identical.
np.random.seed(100)
ten_random_integers = np.random.randint(1,50,10)
print(ten_random_integers)



[ 9 25  4 40 24 16 49 11 31 35]


In [73]:
# Practice 4
# Generate a 3×3 random integer matrix using seed 7.
np.random.seed(7)
random_integer_matrix = np.random.randint(1,50,(3,3))   #(1,50,3*3) incorrect 
print(random_integer_matrix)



[[48  5 26]
 [ 4 20 24]
 [40 29 15]]


In [77]:
# Practice 5
# Change the seed value and observe how the output changes.

np.random.seed(70)
observe1 = np.random.randint(1,50,(3,3))   #(1,50,3*3) incorrect 
print(observe1)
print(' ')

np.random.seed(9)
observe2 = np.random.randint(1,50,(3,3))   #(1,50,3*3) incorrect 
print(observe2)
print(' ')

np.random.seed(0)
observe3 = np.random.randint(1,50,(3,3))   #(1,50,3*3) incorrect 
print(observe3)
print(' ')



[[15 23 25]
 [ 1 22 47]
 [21 40  9]]
 
[[29 23  2]
 [23 41 28]
 [34 30 29]]
 
[[45 48  1]
 [ 4  4 40]
 [10 20 22]]
 


In [ ]:
# Key Takeaways
# np.random.seed() fixes the starting point of random number generation.
# It makes experiments reproducible.
# It is essential in Machine Learning, AI Research, and Thesis work.
# The same seed always produces the same sequence of random numbers.

In [ ]:
#np.reshape() function

In [78]:
# Create a 1D Array
numbers = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

print(numbers)


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [81]:
# Convert 1D → 2D
reshaped_array = numbers.reshape(3,4)
print(reshaped_array )


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [83]:
#Convert into 4×3
reshaped_array = numbers.reshape(4,3)
print(reshaped_array )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [9]:
#Practice Problems
# Create a NumPy array with values from 1 to 16.
# array = np.random.randint(1,17) #incorrect coz its choose  only one vlaue
array = np.array([1, 2, 3, 4,
                  5, 6, 7, 8,
                  9, 10, 11, 12,
                  13, 14, 15, 16]) #1D array
print(array)
#array = np.arange(1,17) alse use this arrage fincton but this fuction not studied erlier thats why i use mnually create 2d array


# Practice 1
# Reshape it into a 4×4 matrix.

# Practice 2
# Reshape it into a 2×8 matrix.

# Practice 3
# Print the shape of the reshaped array.

# Practice 4
# Print the number of dimensions.

# Practice 5
# Try reshape(3,5). What happens?

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]


In [8]:
# Practice 1
# Reshape it into a 4×4 matrix.

reshape_array = array.reshape(4,4)
print(reshape_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [10]:
# Practice 2
# Reshape it into a 2×8 matrix.

reshape_array = array.reshape(2,8)
print(reshape_array)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [11]:
# Practice 3
# Print the shape of the reshaped array.

print(np.shape(reshape_array))

(2, 8)


In [12]:
# Practice 4
# Print the number of dimensions.

print(np.ndim(reshape_array))

2


In [13]:
# Practice 5
# Try reshape(3,5). What happens?

reshape_array = array.reshape(3,5)
print(reshape_array)

#conclusion:  cannot reshape array of size 16 into shape (3,5) coz numoy cant add or revome element 

ValueError: cannot reshape array of size 16 into shape (3,5)

In [ ]:
# Key Takeaways
# reshape() changes only the shape, not the data.
# The total number of elements must remain the same.
# It is widely used in Machine Learning for preparing datasets, images, and features.
# Invalid shapes produce a ValueError.

In [ ]:
# reshape(-1) function

In [14]:
array = np.array([
    1,2,3,4,
    5,6,7,8,
    9,10,11,12
]) #1D array

In [ ]:
# Example 1 — reshape(3,-1)

In [15]:
print(array)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [17]:
reshape_array = array.reshape(3,-1) ## NumPy automatically calculates the number of columns

In [18]:
print (reshape_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Example 2 — reshape(-1,4)

In [20]:
reshape_array = array.reshape(-1,4)

In [21]:
print(reshape_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
# Example 3 — reshape(-1)

In [2]:
matrix = np.array([
    [1,2,3],
    [4,5,6],
])

In [6]:
print(matrix)

[[1 2 3]
 [4 5 6]]


In [8]:
flat_array = matrix.reshape(-1) #np.reshape(-1) previous mistake

In [10]:
print(flat_array) # convert 2D too 1D

[1 2 3 4 5 6]


In [11]:
flat_array = matrix.reshape(-1,-1) #ValueError: can only specify one unknown dimension(NumPy cant undrstand which dimension will be calculate)

ValueError: can only specify one unknown dimension

In [12]:
# Create a NumPy array with values from 1 to 12.

array = np.array([
    1,2,3,4,
    5,6,7,8,
    9,10,11,12
])

# Practice 1
# Reshape the array into 3 rows using -1.

# Practice 2
# Reshape the array into 4 columns using -1.

# Practice 3
# Create a 2×6 matrix and convert it into a 1D array using reshape(-1).

# Practice 4
# Print the shape before reshaping.

# Practice 5
# Print the shape after reshaping.

In [16]:
# Practice 1
# Reshape the array into 3 rows using -1.

reshap_array = array.reshape(-1,4)
print(reshap_array)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [17]:
# Practice 2
# Reshape the array into 4 columns using -1.
reshap_array = array.reshape(3,-1)
print(reshap_array)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [25]:
# Practice 3
# Create a 2×6 matrix and convert it into a 1D array using reshape(-1).

twoD_matrix = np.array([
    [1, 2, 3, 4, 5, 6],
    [7, 8, 9, 10, 11, 12]
])

oneD_array = matrix.reshape(-1) # Convert the matrix into a one-dimensional array
print(twoD_matrix)
print(' ')
print(oneD_array)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
 
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [27]:
# Practice 4
# Print the shape before reshaping.

print(np.shape(twoD_matrix))

(2, 6)


In [28]:
# Practice 5
# Printthe shape after reshaping.

print(np.shape(oneD_array))


(12,)


In [ ]:
# Key Takeaways
# reshape(-1) converts an array into a 1D array.
# reshape(3, -1) tells NumPy to calculate the number of columns automatically.
# reshape(-1, 4) tells NumPy to calculate the number of rows automatically.
# Only one -1 is allowed in a reshape() call.
# This feature is widely used in Machine Learning, Data Preprocessing, and Deep Learning.

In [ ]:
# flatten() vs reshape(-1)

In [32]:
twod_matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])


In [33]:
flat_array = twod_matrix.flatten() 
# Convert the matrix into a one-dimensional array

In [34]:
print(twod_matrix)
print(' ')
print(flat_array)

[[1 2 3]
 [4 5 6]]
 
[1 2 3 4 5 6]


In [35]:

matrix = np.array([
    [1, 2],
    [3, 4]
])



In [45]:
flat = matrix.flatten()

In [46]:
print(flat)

[1 2 3 4]


In [47]:
flat[0] = 100

In [48]:
print(flat)


[100   2   3   4]


In [ ]:
# flatten() vs reshape(-1)

In [14]:
matrix = np.array([
    [1, 2],
    [3, 4]
])

In [6]:
# Example 1 — flatten() (Independent Copy)
flat = matrix.flatten()
flat[0] = 100

In [9]:
print(flat)
print('')
print(matrix)

[100   2   3   4]

[[1 2]
 [3 4]]


In [19]:
# Example 2 — reshape(-1) (View)

view = matrix.reshape(-1)
view[0] = 100

In [20]:
print(view)
print('')
print(matrix) #conclusion reshape(-1) usually the view of Original Data

[100   2   3   4]

[[100   2]
 [  3   4]]


In [29]:
# Create a 2×4 matrix
matrix = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8]
])

# Practice 1
# Convert the matrix into a 1D array using flatten().

# Practice 2
# Print the flattened array.

# Practice 3
# Print the shape of the flattened array.

# Practice 4
# Convert the same matrix into a 1D array using reshape(-1).

# Practice 5
# Compare the outputs of flatten() and reshape(-1).

In [25]:
# Practice 1
# Convert the matrix into a 1D array using flatten().

oneD = matrix.flatten()


In [24]:
# Practice 2
# Print the flattened array.
print(oneD)

[1 2 3 4 5 6 7 8]


In [26]:
# Practice 3
# Print the shape of the flattened array.

print(np.shape(oneD))

(8,)


In [30]:
# Practice 4
# Convert the same matrix into a 1D array using reshape(-1).

oneD = matrix.reshape(-1)
print(oneD)

[1 2 3 4 5 6 7 8]


In [ ]:
# # Practice 5
# # Compare the outputs of flatten() and reshape(-1).
# Both flatten() and reshape(-1) convert a multi-dimensional array into a one-dimensional array. 
# However, flatten() creates a new copy, while reshape(-1) 
# usually creates a view of the original array.

In [ ]:
# Day 5 Final Practice

In [ ]:
# Part A – Random Functions
# # Generate five random numbers between 1 and 100.

# # Generate a 3×3 random matrix.

# # Set the random seed to 42.

# # Generate the same random numbers twice using seed().

In [32]:
# # Generate five random numbers between 1 and 100.

array= np.random.rand(5)
print(array)


[0.02098276 0.76808781 0.95045728 0.534208   0.87080548]


In [34]:
# # Generate a 3×3 random matrix.
matrix = np.random.rand(3,3)
print(matrix)

[[0.2515955  0.48945191 0.68768113]
 [0.73369893 0.46108244 0.97375427]
 [0.95200464 0.81864014 0.61047765]]


In [38]:
# Set the random seed to 42.

np.random.seed(42)
mat = np.random.rand(3,3) #np.random.randint(3,3) this give me a value error
print(mat)

# Conclusion
#
# np.random.rand() and np.random.randint() are different.
#
# - np.random.rand() generates random decimal numbers between
#   0 and 1 and only requires the shape of the array.
#
# - np.random.randint() generates random integers and requires
#   a valid range (low, high). If low is equal to or greater
#   than high, NumPy raises a ValueError.
#
# Understanding the difference between these functions is
# essential for generating random data correctly in Machine
# Learning and Data Science projects.

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [39]:
# # Generate the same random numbers twice using seed().
np.random.seed(41)
mat = np.random.rand(3,3) #np.random.randint(3,3) this give me a value error
print(mat)

[[0.25092362 0.04609582 0.67681624]
 [0.04346949 0.1164237  0.60386569]
 [0.19093066 0.66851572 0.91744785]]


In [ ]:
# Part B – Reshape
# # Create an array from 1 to 12 using np.array().

# # Reshape it into 3×4.

# # Reshape it into 4×3.

# # Use reshape(3, -1).

# # Use reshape(-1, 4).

# # Convert the matrix into a 1D array using reshape(-1).

In [50]:
# # Create an array from 1 to 12 using np.array().

array = np.random.randint(1,12,(1,5)) #its create 1×5 Matrix
print(array) 

array1 = np.random.randint(1,13,12) #its create 1×5 Matrix
print('')
print(array) 


[[ 2  6  4 11  3]]

[11  5 12  2  3  4  5  6  5  6  8  7]


In [51]:
# # Reshape it into 3×4.
reshape_array = array.reshape(3,4)
print(reshape_array) #cannot reshape array of size 5 into shape (3,4) coz array is a 1×5 Matrix

reshape_array = array1.reshape(3,4)
print('')
print(reshape_array)

[[11  5 12  2]
 [ 3  4  5  6]
 [ 5  6  8  7]]


NameError: name 'array1' is not defined

In [52]:
# # Reshape it into 4×3

reshape_array = array.reshape(4,3)
print(reshape_array) #cannot reshape array of size 5 into shape (3,4) coz array is a 1×5 Matrix

reshape_array = array1.reshape(4,3)
print('')
print(reshape_array)

[[11  5 12]
 [ 2  3  4]
 [ 5  6  5]
 [ 6  8  7]]


NameError: name 'array1' is not defined

In [54]:
# # Usereshape(3, -1)

reshape_array = array.reshape(3,-1)
print(reshape_array)

[[11  5 12  2]
 [ 3  4  5  6]
 [ 5  6  8  7]]


In [57]:
# # Use reshape(-1, 4).

reshape_array = array.reshape(-1,4)
print(reshape_array)

[[11  5 12  2]
 [ 3  4  5  6]
 [ 5  6  8  7]]


In [59]:
# # Convertthe matrix into a 1D array using reshape(-1)

print(array.reshape(-1))

[11  5 12  2  3  4  5  6  5  6  8  7]


In [ ]:
# Part C – Flatten
# # Create a 2×4 matrix.

# # Convert it into a 1D array using flatten().

# # Print the original matrix.

# # Print the flattened array.

In [62]:
# # Create a 2×4 matrix.

array = np.random.randint(1,15,(2,4))
print(array)

[[11  7 11  2]
 [ 5 10 10  6]]


In [66]:
# # Convert it into a 1D array using flatten().
flat = array.flatten()
print(flat)

[11  7 11  2  5 10 10  6]


In [65]:
# # Print the original matrix.
print(array)

[[11  7 11  2]
 [ 5 10 10  6]]


In [67]:
# # Print the flattened array.
print(flat)

[11  7 11  2  5 10 10  6]
