In [1]:
import numpy as np

In [5]:
arr = np.array([20,60,79,89,90,])


In [9]:
sum = np.sum(arr)
print(sum)

338


In [10]:
np.sum(arr)
print(arr)

[20 60 79 89 90]


In [ ]:
#calculationg sum of students marks using np.sum() dunction

In [11]:
marks = np.array([78,90,89,98,78,76])# Create an array containing students' marks

In [12]:
total_marks = np.sum(marks)# Calculate the total marks

In [13]:
print(total_marks) # Display the result

509


In [14]:
# Practice Problems
practice_sum = np.array([12, 25, 18, 30, 45])
# Print the entire array.
# Calculate the total sum.
# Store the result in a variable named total.
# Print the variable total.

In [15]:
print(practice_sum)

[12 25 18 30 45]


In [17]:
total = np.sum(practice_sum)

In [18]:
print(total)

130


In [ ]:
#np.mean() function in numpy

In [19]:
temperature = np.array([10,20,30,40,50])# Create an array containing temperature

In [20]:
average_temperature = np.mean(temperature)# Calculate the average value of the array

In [21]:
print(average_temperature)# Display the average temperature

30.0


In [22]:
# Practice Problems of np.mean() function
practice_mean = np.array([10, 20, 30, 40, 50])
# Print the entire array.
# Calculate the average value.
# Store the result in a variable named average.
# Print the variable average.


In [23]:
print(practice_mean)

[10 20 30 40 50]


In [24]:
average = np.mean(practice_mean)

In [25]:
print(average)

30.0


In [ ]:
#np.min() function

In [6]:
temperature = np.array([36.5, 37.2, 38.1, 36.8, 39.0]) # Create an array containing temperature

In [27]:
np.min(temperature)  # Find the minimum value in the temperature array

np.float64(36.5)

In [29]:
minimum_temp = np.min(temperature) # Display the minimum value

In [9]:
mximum_temp = np.max(temperature) # Display the maximum value

In [30]:
print(minimum_temp) # Display the minimum temperature value

36.5


In [10]:
print(mximum_temp)

39.0


In [11]:
# Practice Problems of min() & max() functions
practice = np.array([15, 42, 8, 67, 29, 53])
# Print the entire array.
# Find the minimum value.
# Find the maximum value.
# Store the minimum value in a variable named minimum.
# Store the maximum value in a variable named maximum.
# Print both variables.

In [12]:
print(practice)

[15 42  8 67 29 53]


In [13]:
minimum = np.min(practice)

In [17]:
maximum = np.max(practice)

In [14]:
print(minimum)

8


In [18]:
print(maximum)

67


In [19]:
#np.median()

In [20]:
marks = np.array([85, 90, 88, 78, 92]) # Create an array containing students' marks

In [21]:
median_mark = np.median(marks)  # Calculate the median value

In [22]:
print( median_mark) # Display the median value

88.0


In [24]:
#  Practice Problems using np.mean() functions
practice_median = np.array([12, 18, 25, 30, 100])
# Print the entire array.
# Calculate the median.
# Store the result in a variable named median_value.
# Print median_value.
# Compare the Mean and Median. Which one is more affected by the value 100?

In [25]:
print(practice_median)

[ 12  18  25  30 100]


In [28]:
median_value = np.median(practice_median)

In [29]:
print(median_value)

25.0


In [30]:
mean_value = np.mean(practice_median)

In [31]:
print(mean_value) #mean is affected by outlier which is 100

37.0


In [ ]:
#np.std() function ; standard deviation

In [2]:
marks = np.array([85, 90, 88, 78, 92]) # Create an array containing students' marks

In [3]:
std_value = np.std(marks) # Calculate the standard deviation

In [4]:
print(std_value) # Display the standard deviation

4.882622246293481


In [5]:
# Practice Problems using np.std() function

practice_std = np.array([12, 15, 18, 20, 25])


# Print the entire array.
# Calculate the standard deviation.
# Store the result in a variable named std_result.
# Print std_result.
# Is the data closely grouped or widely spread? Explain your answer.


In [6]:
print(practice_std)

[12 15 18 20 25]


In [7]:
 std_result = np.std(practice_std)

In [8]:
print(std_result) 

4.427188724235731


In [ ]:
# The data is relatively closely grouped because the standard deviation is low. This indicates that most values are close to the mean and there is no large variation in the dataset.
# Low Standard Deviation → Closely Grouped Data
# High Standard Deviation → Widely Spread Data  

In [ ]:
# np.var() (Variance)

In [9]:
marks = np.array([85, 90, 88, 78, 92]) # Create an array containing students' marks

In [10]:
variance_value = np.var(marks) # Calculate the variance of the array

In [11]:
print(variance_value) # Display the variance

23.839999999999996


In [13]:
# Practice Problems of np.var() functions

practice_var = np.array([12, 15, 18, 20, 25])

# Print the entire array.
# Calculate the variance.
# Store the result in a variable named variance_result.
# Print variance_result.
# Compare the variance with the standard deviation. What is their relationship?

In [14]:
print(practice_var)

[12 15 18 20 25]


In [18]:
variance_result = np.var(practice_var)
sd = np.std(practice_var)

In [19]:
print(variance_result)
print(sd)

19.6
4.427188724235731


In [ ]:
Variance is the square of the standard deviation. For example, if the standard deviation is 4.42, then the variance is 19.6.

In [ ]:
#np.sqrt() function

In [23]:
numbers = np.array([25, 49, 64, 81]) 
# Create an array containing perfect square numbers

In [21]:
square_root = np.sqrt(numbers) # Calculate the square root of each element

In [22]:
print(square_root)# Display the square root values

[5. 7. 8. 9.]


In [25]:
# Practice Problems
    
practice_sqrt = np.array([4, 9, 16, 25, 36])

# Try solving these:

# Print the entire array.
# Calculate the square root of all elements.
# Store the result in a variable named sqrt_result.
# Print sqrt_result.
# # Explain why np.sqrt() is important in Machine Learning.

In [26]:
print(practice_sqrt)

[ 4  9 16 25 36]


In [27]:
sqrt_result = np.sqrt(practice_sqrt)

In [29]:
print(sqrt_result) # np.sqrt() returns floating-point values, so integers are displayed as 2., 3., 4., etc. (equivalent to 2.0, 3.0, 4.0).

[2. 3. 4. 5. 6.]


In [ ]:
# np.sqrt() is important in Machine Learning because it is used to calculate standard deviation, Euclidean distance, and other mathematical operations used in data preprocessing and machine learning algorithms.

In [ ]:
#np.power() function

In [30]:
numbers = np.array([2, 3, 4, 5]) #create 1D array

In [31]:
square = np.power(numbers, 2) # Raise each element to the power of 2

In [32]:
print(square) # Display the squared values

[ 4  9 16 25]


In [34]:
# Practice Problems

practice_power = np.array([2, 4, 6, 8])

# Print the entire array.
# Raise all elements to the power of 2.
# Store the result in a variable named power_result.
# Print power_result.
# Explain why np.power() is useful in Machine Learning.

In [37]:
print(practice_power)

[2 4 6 8]


In [39]:
power_result = np.power(practice_power,2)

In [40]:
print(power_result)

[ 4 16 36 64]


In [ ]:
# np.power() is useful in Machine Learning because it is used to create polynomial features and perform mathematical calculations such as variance and distance formulas.

In [ ]:
#np.abs() function

In [41]:
numbers = np.array([-8, -3, 5, 10]) # Create an array containing positive and negative numbers

In [42]:
absolute_values = np.abs(numbers) # Calculate the absolute value of each element


In [44]:
print(absolute_values) # Display the absolute values

[ 8  3  5 10]


In [45]:
# Practice Problems using np.abs

practice_abs = np.array([-15, -8, 0, 12, -20])

# Print the entire array.
# Calculate the absolute value of all elements.
# Store the result in a variable named abs_result.
# Print abs_result.
# Explain why np.abs() is useful in Machine Learning.

In [48]:
print(practice_abs)

[-15  -8   0  12 -20]


In [49]:
abs_result = np.abs(practice_abs)

In [50]:
print(abs_result)

[15  8  0 12 20]


In [ ]:

# np.abs() is useful in Machine Learning because it measures the magnitude of errors without considering whether they are positive or negative.


In [ ]:
#np.round() finction

In [52]:
numbers = np.array([3.14159, 5.67891, 8.23456])  # Create an array containing decimal numbers

In [54]:
rounded_numbers = np.round(numbers, 2)  
# Round each element to two decimal places

In [56]:
print(rounded_numbers) # Display the rounded values

[3.14 5.68 8.23]


In [57]:
# Practice Problems solve to use np.round() function

practice_round = np.array([2.3456, 5.6789, 8.9123, 10.4567])

# Try solving these:

# Print the entire array.
# Round all values to 2 decimal places.
# Store the result in a variable named round_result.
# Print round_result.
# Explain why np.round() is useful in Machine Learning.

In [58]:
print(practice_round )

[ 2.3456  5.6789  8.9123 10.4567]


In [59]:
round_result = np.round(practice_round ,2)

In [60]:
print(round_result)


[ 2.35  5.68  8.91 10.46]


In [ ]:
# np.round() is useful in Machine Learning because it makes numerical results easier to read and present by reducing unnecessary decimal places.

In [ ]:
#np.ceil function

In [61]:
numbers = np.array([2.3,4.8,6.1 ,7.9]) # Create an array containing decimal numbers

In [62]:
ceil_value = np.ceil(numbers) # Round each value up to the nearest integer

In [64]:
print(ceil_value ) # print the ceiling values

[3. 5. 7. 8.]


In [66]:
# Practice Problems

practice_ceil = np.array([1.2, 3.7, 5.1, 8.9])

# Print the entire array.
# Apply np.ceil() to all elements.
# Store the result in a variable named ceil_result.
# Print ceil_result.
# Explain why np.ceil() is useful in real-life applications.


In [68]:
print(practice_ceil)

[1.2 3.7 5.1 8.9]


In [69]:
ceil_result = np.ceil(practice_ceil)

In [70]:
print(ceil_result)

[2. 4. 6. 9.]


In [ ]:
# np.ceil() is useful because it rounds values up to ensure enough resources are available, such as seats, packets, or memory allocation.

In [71]:
#np.floor() function

In [72]:
numbers = np.array([2.3, 4.8, 6.1, 7.9]) #create array

In [73]:
floor_values = np.floor(numbers) # Round each value down to the next lower integer


In [75]:
print(floor_values) #print

[2. 4. 6. 7.]


In [76]:
# Practice Problems

practice_floor = np.array([2.8, 5.4, 7.9, 10.2])

# Print the entire array.
# Apply np.floor() to all elements.
# Store the result in a variable named floor_result.
# Print floor_result.
# Explain why np.floor() is useful in real-life applications.

In [77]:
print(practice_floor)

[ 2.8  5.4  7.9 10.2]


In [79]:
 floor_result = np.floor(practice_floor)

In [80]:
print( floor_resul)

[ 2.  5.  7. 10.]


In [81]:
# np.floor() is useful because it rounds values down to the nearest integer when only completed or whole units are needed.

In [82]:
#  axis = 0 (Column-wise)

In [83]:
# Create a two-dimensional NumPy array
marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 89, 95]
])


In [84]:
column_sum = np.sum(marks, axis=0) # Calculate the sum of each column

In [85]:
print(column_sum) # print the column-wise sum

[255 261 263]


In [ ]:
#  axis = 1 (Rowwise)

In [86]:
row_sum = np.sum(marks, axis=1) # Calculate the sum of each row

In [87]:
print(row_sum) # print the row-wise sum

[263 240 276]


In [88]:
# Practice Problems on axis = 0

practice_axis = np.array([
     [10, 20, 30],
     [40, 50, 60],
     [70, 80, 90]
 ])

# Try solving these:

# Print the entire array.
# Calculate the sum of each row.
# Store the result in a variable named row_sum.
# Print row_sum.
# Explain the difference between axis=0 and axis=1.

In [89]:
print(practice_axis)

[[10 20 30]
 [40 50 60]
 [70 80 90]]


In [90]:
row_sum = np.sum(practice_axis,axis=1)

In [91]:
print(row_sum)

[ 60 150 240]


In [ ]:
# axis=0 performs calculations on columns, while axis=1 performs calculations on rows.

In [ ]:
# Real Machine Learning Examples

In [92]:
# Example 1 – Student Marks Analysis
# Create a dataset of student marks
marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 89, 95]
])
# Calculate the total marks of each student
# Calculate the average marks of each subject
# Find the highest mark in the dataset
# Find the lowest mark in the dataset

In [93]:
student_total_marks = np.sum(marks,axis=1)

In [95]:
print(student_total_marks)

[263 240 276]


In [96]:
student_average_mark = np.mean(marks,axis=1)

In [97]:
print(student_average_mark)

[87.66666667 80.         92.        ]


In [99]:
print(np.max(marks))

95


In [100]:
print(np.min(marks))

78


In [103]:
# Example 2 – Machine Learning Feature Analysis of Height Dataset

height = np.array([160, 165, 170, 175, 180])
# Calculate the average height
# Calculate the standard deviation
# Calculate the variance

In [104]:
print(np.mean(height))

170.0


In [105]:
print(np.std(height))

7.0710678118654755


In [106]:
print(np.var(height))

50.0


In [107]:
# Example 3 – Krishok Bondhu App Analysis of rice production

production = np.array([120.456, 140.782, 135.219])

# Round the production values to two decimal places

In [108]:
print(np.round(production,2))

[120.46 140.78 135.22]


In [110]:
# Example 4 – Mean Absolute Error (MAE)

prediction = np.array([90, 85, 80])
actual = np.array([88, 90, 82])

# Calculate the absolute error
# Calculate the mean absolute error

In [111]:
error = np.abs(prediction - actual)

In [112]:
print(error)

[2 5 2]


In [113]:
print(np.mean(error))

3.0


In [ ]:
# Example 5 – Batch Size Calculation
# let
# 1000 Images and batch size is 128
# Calculate the required number of batches

In [114]:
print(np.ceil(1000 / 128))

8.0


In [115]:
#Example 6 – Feature Scaling(Square Root Transformation)
feature = np.array([4, 9, 16, 25])

# Apply square root transformation

In [116]:
print(np.sqrt(feature))

[2. 3. 4. 5.]


In [133]:
# Mixed Practice Challenge
marks = np.array([
    [85, 90, 88],
    [78, 82, 80],
    [92, 89, 95]
])

# Practice Questions


# Part A – Basic Operations

# Print the entire array.
# Print the shape of the array.
# Print the number of dimensions.
# Print the data type.

# Part B – Statistical Functions

# Calculate the total sum of all elements.
# Calculate the average of all elements.
# Find the maximum value.
# Find the minimum value.
# Find the median.
# Calculate the standard deviation.
# Calculate the variance.

# Part C – Mathematical Functions

# Calculate the square root of every element.
# Square every element using np.power().
# Create the following array and find its absolute values.

difference = np.array([-5, -3, 2, -8, 6])

# Part D – Rounding Functions

# Create the following array.
 
numbers = np.array([3.4567, 8.9231, 5.1289])

# Round all numbers to 2 decimal places.
# Apply np.ceil().
# Apply np.floor().

# Part E – Axis Operations

# Calculate the sum of each column.
# Calculate the sum of each row.
# Calculate the average of each column.
# Calculate the average of each row.

# Part F – Concept Questions

# Why is np.mean() important in Machine Learning?
# When should we use np.median() instead of np.mean()?
# What does Standard Deviation tell us?
# What is the relationship between Variance and Standard Deviation?
# What is the difference between np.ceil() and np.floor()?
# What is the difference between axis=0 and axis=1?


In [ ]:
#  Solution of Part A – Basic Operations

In [117]:
print(marks) #print the entire array.

[[85 90 88]
 [78 82 80]
 [92 89 95]]


In [118]:
print(np.shape( marks)) #print the shape of the array.

(3, 3)


In [119]:
print(marks.ndim) #print the number of dimensions.

2


In [120]:
print(marks.dtype) # print data type


int64


In [ ]:
# Solution of Part B – Statistical Functions

In [121]:
print(np.sum(marks)) # Calculate the total sum of all elements

779


In [ ]:
print(np.mean(marks)) #Calculate the average of all elements

In [123]:
print(np.max(marks)) #Find the maximum value

95


In [124]:
print(np.min(marks)) #Find the minimum value

78


In [125]:
print(np.mean(marks)) #Find the median

86.55555555555556


In [ ]:
print(np.std(marks)) #Calculate the standard deviation

In [126]:
print(np.var(marks)) #Calculate the variance

28.913580246913583


In [ ]:
#Solution of Part C – Mathematical Functions

In [127]:
print(np.sqrt(marks)) #Calculate the square root of every element

[[9.21954446 9.48683298 9.38083152]
 [8.83176087 9.05538514 8.94427191]
 [9.59166305 9.43398113 9.74679434]]


In [129]:
print(np.power(marks, 2)) #Square every element

[[7225 8100 7744]
 [6084 6724 6400]
 [8464 7921 9025]]


In [131]:
print(np.abs(difference)) #Find the absolute values

[5 3 2 8 6]


In [ ]:
# Solution of Part D – Rounding Functions

In [134]:
print(numbers)

[3.4567 8.9231 5.1289]


In [136]:
print(np.round(numbers, 2)) #Round to 2 decimal places

[3.46 8.92 5.13]


In [138]:
print(np.ceil(numbers)) #Apply np.ceil()

[4. 9. 6.]


In [139]:
print(np.floor(numbers)) #Apply np.floor()

[3. 8. 5.]


In [ ]:
#Solution of Part E – Axis Operations

In [140]:
print(np.sum(marks,axis=0)) #Calculate the sum of each column

[255 261 263]


In [141]:
print(np.sum(marks,axis=1)) #Calculate the sum of each row

[263 240 276]


In [143]:
print(np.mean(marks,axis=0)) #Calculate the average of each column

[85.         87.         87.66666667]


In [144]:
print(np.mean(marks,axis=1)) #Calculate the average of each row

[87.66666667 80.         92.        ]
